version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"  # Node.js service
      - "8000:8000"  # Python FastAPI service
    environment:
      - NODE_ENV=development
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=postgres
      - DB_PORT=5432
    volumes:
      - .:/app
      - /app/node_modules
      - /app/__pycache__
      - temp_data:/app/temp
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5436:5436"
    command: -p 5436
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -p 5436"]

volumes:
  postgres_data:
  temp_data: 